# Generated by Django 5.0.2 on 2024-07-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
